#23Januari2023

#EXTM3U

#EXTM3U

#EXTINF:-1 group-title="HD Channel"
#EXTINF:-1 group-title="Dolby"
#EXTINF:-1 group-title="Local Channel"
#EXTINF:-1 group-title="Sports"
#EXTINF:-1 group-title="Movies"
#EXTINF:-1 group-title="Kids"
#EXTINF:-1 group-title="Gen Entertainment"
#EXTINF:-1 group-title="Lifestyle"
#EXTINF:-1 group-title="Knowledge"
#EXTINF:-1 group-title="Music"
#EXTINF:-1 group-title="News"
#EXTINF:-1 group-title="Religious"

#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/useemozaik.png" group-title="Local Channel",2 Mozaik Channel
rtp://@239.1.2.223:9268
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_useesport_newlogo.png" group-title="Sports",85 USee Sports HD
rtp://@239.1.2.203:9180
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_useesports2_newlogo.png" group-title="Sports",86 Usee Sports 2 HD
rtp://@239.1.2.205:9186
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_seatoday_big.png" group-title="Local Channel",87 SEA Today HD
rtp://@239.1.2.70:8396
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_useeprime_big1.png" group-title="Local Channel",88 USee Prime HD
rtp://@239.1.1.252:9486
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_tvri_big1.png" group-title="Local Channel",100 TVRI HD
rtp://@239.1.1.238:8016
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-metrotv.png" group-title="Local Channel",101 Metro TV HD
rtp://@239.1.2.2:7986
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_cnnindonesia_big1.png" group-title="Local Channel",102 CNN Indonesia HD
rtp://@239.1.1.180:9054
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-tvone-big1.png" group-title="Local Channel",103 TV One
rtp://@239.1.1.31:8160
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-transtv-big1.png" group-title="Local Channel",104 Trans TV HD
rtp://@239.1.1.194:9138
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-trans7-big1.png" group-title="Local Channel",105 Trans 7 HD
rtp://@239.1.1.222:9306
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/lejelhome.png" group-title="Lifestyle",106 Lejel Home Shopping (Live)
rtp://@239.1.2.3:7992
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-sctv-big1.png" group-title="Local Channel",107 SCTV HD
rtp://@239.1.2.58:8324
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-antv-big1.png" group-title="Local Channel",108 ANTV
rtp://@239.1.1.15:8064
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-indosiar-big1.png" group-title="Local Channel",109 Indosiar HD
rtp://@239.1.1.214:8010
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/lejelhome.png" group-title="Lifestyle",110 Lejel Home Shopping
rtp://@239.1.1.3:7992
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_net_big1.png" group-title="Local Channel",112 Net TV HD
rtp://@239.1.1.158:8922
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_dramakorealbs_big.png" group-title="Gen Entertainment",113 Drama Korea LBS
rtp://@239.1.2.101:9521
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-kompastv-big1.png" group-title="Local Channel",114 Kompas TV HD
rtp://@239.1.1.240:8017
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_beritasatu_big1.png" group-title="Local Channel",115 BTV HD
rtp://@239.1.1.114:9512
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_jaktv_big1.png" group-title="Local Channel",116 Jak TV
rtp://@239.1.1.107:8616
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_iberkah.png" group-title="Local Channel",117 iBerkah
rtp://@239.1.1.12:7984
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-rtv-big1.png" group-title="Local Channel",118 RTV HD
rtp://@239.1.1.253:8018
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_idx_big.png" group-title="Local Channel",119 IDX Channel
rtp://@239.1.2.248:9398
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_daaitv_big1.png" group-title="Local Channel",120 Daai TV
rtp://@239.1.1.179:9048
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-atv-big1.png" group-title="Local Channel",121 ATV
rtp://@239.1.2.88:8308
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_balitv_big1.png" group-title="Local Channel",122 Bali TV
rtp://@239.1.1.72:8406
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_jtv_big1.png" group-title="Local Channel",123 JTV
rtp://@239.1.1.6:8010
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_antara_big1.png" group-title="Local Channel",124 Antara HD
rtp://@239.1.1.104:9511
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_ochannel_big.png" group-title="Local Channel",125 Moji HD
rtp://@239.1.1.10:9513
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_tvedukasi_big1.png" group-title="Local Channel",127 TV Edukasi
rtp://@239.1.1.39:8208
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_nusantaratv_big.png" group-title="Local Channel",128 Nusantara TV
rtp://@239.1.2.102:9522
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_inews_big.png" group-title="Local Channel",129 iNews
rtp://@239.1.1.212:8967
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_rri_big1.png" group-title="Local Channel",130 RRI Net
rtp://@239.1.2.74:8420
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_gprtv_big1.png" group-title="Local Channel",131 GPR TV
rtp://@239.1.2.17:9379
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_garudatv_big.png" group-title="Local Channel",133 Garuda TV
rtp://@239.1.1.164:8965
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_mncnews2_big.png" group-title="Local Channel",134 MNC News
rtp://@239.1.1.146:7985
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_cnbcid_big.png" group-title="Local Channel",135 CNBC Indonesia HD
rtp://@239.1.2.94:9448
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_Jowo_channel.png" group-title="Local Channel",137 Jowo
rtp://@239.1.2.6:8000
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_indonesiana_big.png" group-title="Local Channel",200 Indonesiana TV
rtp://@239.1.1.206:9199
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_natgeo_big.png" group-title="Knowledge",201 National Geographic HD
rtp://239.1.1.243:9432
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_natgeowild_big.png" group-title="Knowledge",202 Natgeo Wild HD
rtp://@239.1.1.207:9216
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/crimeinvestigation.png" group-title="Knowledge",203 Crime & Investigation HD
rtp://@239.1.1.223:8012
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_cgtndocumentary_big1.png" group-title="Knowledge",204 CGTN Documentary HD
rtp://@239.1.2.4:7998
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_history_big.png" group-title="Knowledge",205 History Channel HD
rtp://@239.1.1.23:8112
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/pandatv.png" group-title="Knowledge",206 Panda TV
rtp://@239.1.1.208:9502
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_discovery_big.png" group-title="Knowledge",207 Discovery HD
rtp://@239.1.1.247:9440
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_lingua_big.png" group-title="Knowledge",208 Lingua
rtp://@239.1.2.90:9500
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-techstorm_big.png" group-title="Knowledge",209 TechStorm HD
rtp://@239.1.2.229:9330
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_davinci_big1.png" group-title="Kids",303 Da Vinci HD
rtp://@239.1.1.218:8011
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_nickelodeon_big.png" group-title="Kids",304 Nickelodeon HD
rtp://@239.1.1.14:7982
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_nickjr_big.png" group-title="Kids",305 Nick Junior HD
rtp://@239.1.1.162:7983
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_cartoonnetwork_big.png" group-title="Kids",306 Cartoon Network HD
rtp://@239.1.2.81:8083
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_boomerang_big.png" group-title="Kids",308 Boomerang HD
rtp://@239.1.1.163:8084
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_dreamworks_big1.png" group-title="Kids",310 Dream Work HD
rtp://@239.1.1.234:9222
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_moonbug_big.png" group-title="Kids",311 Moonbug Kids HD
rtp://@239.1.1.235:8593
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_duniaanak_big1.png" group-title="Kids",312 Dunia Anak
rtp://@239.1.1.7:8016
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_mykids_big.png" group-title="Kids",313 MY KIDZ HD
rtp://@239.1.1.52:8416
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_indikids_big.png" group-title="Kids",314 indi kids HD
rtp://@239.1.1.201:9180
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_horee_big.png" group-title="Kids",315 Horee! HD
rtp://@239.1.1.225:8013
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_mentaritv_big.png" group-title="Kids",316 Mentari TV HD
rtp://@239.1.1.140:9515
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_afc_big.png" group-title="Lifestyle",402 AFN HD
rtp://@239.1.2.13:8052
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_eatgo_big1.png" group-title="Lifestyle",403 Eat & Go
rtp://@239.1.1.229:9350
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_fashiontv_big1.png" group-title="Lifestyle",404 Fashion TV HD
rtp://@239.1.2.237:9348
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-tlc_big.png" group-title="Gen Entertainment",406 TLC HD
rtp://@239.1.2.235:9342
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_mtvlive_big.png" group-title="Music",450 MTV Live HD
rtp://@239.1.2.16:8070
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_musikindo_big.png" group-title="Music",451 Musik Indonesia
rtp://@239.1.2.108:9523
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_prambors_big1.png" group-title="Music",453 Prambors HD
rtp://@239.1.1.254:8019
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_ikonser_big.png" group-title="Music",459 i Konser HD
rtp://@239.1.2.221:9250
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_hgtv_big.png" group-title="Gen Entertainment",500 HGTV HD
rtp://@239.1.2.34:8178
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_blueantext_big.png" group-title="Movies",501 Rock Action HD
rtp://@239.1.1.112:8646
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_animax_big.png" group-title="Gen Entertainment",502 Animax HD
rtp://@239.1.1.142:8967
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_insert_big1.png" group-title="Local Channel",503 Insert
rtp://@239.1.1.113:8652
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_seru_big.png" group-title="Gen Entertainment",504 Seru!
rtp://@239.1.2.109:9524
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_lifetime_big.png" group-title="Gen Entertainment",505 Lifetime HD
rtp://@239.1.1.25:8124
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_kix_big.png" group-title="Gen Entertainment",506 KIX HD
rtp://@239.1.2.207:9190
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-hits_big.png" group-title="Gen Entertainment",507 Hits HD
rtp://@239.1.1.209:9228
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_warner_big.png" group-title="Gen Entertainment",508 Warner HD
rtp://@239.1.2.244:9078
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_axn_big.png" group-title="Gen Entertainment",509 AXN HD
rtp://@239.1.1.245:9436
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_tv5monde_big1.png" group-title="Gen Entertainment",510 TV5Monde
rtp://@239.1.1.55:8300
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_blueant_big.png" group-title="Gen Entertainment",511 Rock Entertainment HD
rtp://@239.1.2.76:9310
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_tvn_big.png" group-title="Gen Entertainment",516 TVN HD
rtp://@239.1.2.211:9202
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/kbsworld.png" group-title="Gen Entertainment",517 KBS World HD
rtp://@239.1.1.13:8052
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_aniplus_big1.png" group-title="Gen Entertainment",518 Aniplus HD
rtp://@239.1.2.104:9526
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_nhkworld_big1.png" group-title="Gen Entertainment",519 NHK World Premium HD
rtp://@239.1.1.174:9018
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_kplus_big1.png" group-title="Gen Entertainment",523 K+ HD
rtp://@239.1.1.202:9186
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_formosa_big.png" group-title="Gen Entertainment",524 Formosa 
rtp://@239.1.2.198:9386
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_ctiasia_big.png" group-title="Gen Entertainment",526 CTI Asia
rtp://@239.1.2.200:9168
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_dunialain_big.png" group-title="Gen Entertainment",527 Dunia Lain
rtp://@239.1.1.149:8868
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_abcaustralia_big.png" group-title="Gen Entertainment",531 ABC Australia HD
rtp://@239.1.1.26:9519
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_arirang_big.png" group-title="Gen Entertainment",532 Arirang HD
rtp://@239.1.2.107:9522
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_cctv4_big1.png" group-title="Gen Entertainment",533 CCTV4
rtp://@239.1.1.115:8664
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_citradrama_big.png" group-title="Gen Entertainment",534 Citra Drama HD
rtp://@239.1.1.230:9516
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_citradangdut_big.png" group-title="Music",535 Citra Dangdut HD
rtp://@239.1.1.24:9517
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_sgem_big.png" group-title="Gen Entertainment",536 Gem HD
rtp://@239.1.2.18:8082
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_sone_big.png" group-title="Movies",537 One HD
rtp://@239.1.2.21:8100
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/Zhejiang-Television.png" group-title="Gen Entertainment",538 Zhejiang International
rtp://@239.1.1.154:8898
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/Shenzen-Television.png" group-title="Gen Entertainment",539 Shenzen International
rtp://@239.1.1.156:8910
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_ebcasia_big.png" group-title="Gen Entertainment",540 EBC Asia
rtp://@239.1.2.196:9406
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/kungfutv.png" group-title="Gen Entertainment",541 NewTV
rtp://@239.1.2.40:8206
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_chinesedrama_big.png" group-title="Gen Entertainment",542 Chinese Drama
rtp://@239.1.2.10:8306
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-paramount_big.png" group-title="Movies",600 Paramount HD
rtp://@239.1.1.211:9240
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hbo.png" group-title="Movies",601 HBO HD
rtp://@239.1.1.203:9192
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hbosignature.png" group-title="Movies",602 HBO Signature HD
rtp://@239.1.2.249:9378
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/cinemax.png" group-title="Movies",603 Cinemax HD
rtp://@239.1.2.247:9372
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hbohits.png" group-title="Movies",604 HBO Hits HD
rtp://@239.1.1.215:9264
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hbofamily.png" group-title="Movies",605 HBO Family HD
rtp://@239.1.2.245:9366
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-hitsmovie_big.png" group-title="Movies",606 Hits Movies HD
rtp://@239.1.1.190:9116
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_thrill_big.png" group-title="Movies",610 Thrill
rtp://@239.1.1.83:8472
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/celectial.png" group-title="Movies",611 Celestial Movies HD
rtp://@239.1.1.232:8014
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-mycinema_big.png" group-title="Movies",612 My Cinema HD
rtp://@239.1.2.225:9318
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/tvnmovie.png" group-title="Movies",613 TVN Movies HD
rtp://@239.1.2.72:8408
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_zbioskop_big1.png" group-title="Movies",614 Zee Bioskop
rtp://@239.1.1.129:8748
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/cinemaworld.png" group-title="Movies",615 Cinema World HD
rtp://@239.1.2.80:8578
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-myfamily_big.png" group-title="Movies",616 My Family Channel HD
rtp://@239.1.1.237:9396
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_galaxy_big1.png" group-title="Movies",617 Galaxy HD
rtp://@239.1.1.136:8790
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_bioskopindonesia_big1.png" group-title="Movies",618 Bioskop Indonesia
rtp://@239.1.1.226:9332
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_flik_big1.png" group-title="Movies",619 Flik HD
rtp://@239.1.1.239:9276
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_imc_big.png" group-title="Movies",620 IMC HD
rtp://@239.1.1.145:8844
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_galaxypremium_big.png" group-title="Movies",621 Galaxy Prenium HD
rtp://@239.1.2.100:9518
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-mycinemaasia_big.png" group-title="Movies",624 My Cinema Asia HD
rtp://@239.1.1.231:8062
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-bein1-big1.png" group-title="Sports",701 Bein 1 HD
rtp://@239.1.1.248:9494
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-bein3-big1.png" group-title="Sports",702 Bein 3 HD
rtp://@239.1.1.249:9496
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_fight_big1.png" group-title="Sports",704 Fight Sport HD
rtp://@239.1.2.209:9196
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_spotv_big.png" group-title="Sports",705 SPOTV HD
rtp://@239.1.1.109:8623
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_spotv2_big.png" group-title="Sports",706 SPOTV 2 HD
rtp://@239.1.1.196:9145
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_nba_big1.png" group-title="Sports",708 NBA TV HD
rtp://@239.1.2.210:9444
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-horizonsport_big.png" group-title="Sports",714 Horizon Sports HD
rtp://@239.1.2.201:9174

==kuncoro

#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_euronews_big1.png" group-title="News",800 Euronews
rtp://@239.1.1.193:9132
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_cnninternational_big.png" group-title="News",801 CNN HD
rtp://@239.1.1.246:9438
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_bloomberg_big1.png" group-title="News",802 Bloomberg HD
rtp://@239.1.2.105:9520
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_cnbcasias_big.png" group-title="News",803 CNBC Asia HD
rtp://@239.1.1.46:8413
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_newsasia_big1.png" group-title="News",804 Channel News Asia HD
rtp://@239.1.2.23:8112
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_aljazeera_big1.png" group-title="News",805 Aljazeera HD
rtp://@239.1.2.8:8022
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_france24_big.png" group-title="News",806 France24 HD
rtp://@239.1.2.22:8106
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_nhkworld_big.png" group-title="Gen Entertainment",807 NHK World Japan HD
rtp://@239.1.2.239:9354
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_dwtv_big.png" group-title="News",808 DW HD
rtp://@239.1.2.243:9360
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_tvbsnews_big.png" group-title="News",809 TVBS News HD
rtp://@239.1.1.48:8414
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_trtworld_small.png" group-title="News",810 TRT World HD
rtp://@239.1.1.250:9518
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_alquran_big1.png" group-title="Religious",850 AlQuran Karim
rtp://@239.1.1.185:9084
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_rodjatv_big1.png" group-title="Religious",852 Rodja TV
rtp://@239.1.1.224:9320
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_mtatv_big1.png" group-title="Religious",853 MT@ TV
rtp://@239.1.2.234:9374
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_mqtv_big1.png" group-title="Religious",854 MQTV
rtp://@239.1.1.213:9252
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_tv9_big1.png" group-title="Religious",855 TV9
rtp://@239.1.1.150:8874
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_muhammadiyahtv_big1.png" group-title="Religious",856 tvMu
rtp://@239.1.1.170:8994
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_tawaftv_big.png" group-title="Religious",858 Tawaf TV
rtp://@239.1.2.236:9366
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_tvmui_big1.png" group-title="Religious",860 TV MUI
rtp://@239.1.2.52:8286
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hope.png" group-title="Religious",870 Hope
rtp://@239.1.1.78:8442
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_uchannel_big1.png" group-title="Religious",871 U Channel
rtp://@239.1.1.220:9522
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_rri_big1.png" group-title="Local Channel",887 RRI Net HD
rtp://@239.1.1.130:9514
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hbo.png" group-title="Movies",891 HBO Dolby HD
rtp://@239.1.2.114:9428
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hbosignature.png" group-title="Movies",892 HBO Signature Dolby HD
rtp://@239.1.2.116:9404
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hbohits.png" group-title="Movies",893 HBO Hits Dolby HD
rtp://@239.1.2.204:9182
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hbofamily.png" group-title="Movies",894 HBO Family Dolby HD
rtp://@239.1.2.202:9176
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/cinemax.png" group-title="Movies",895 Cinemax Dolby HD
rtp://@239.1.2.206:9186
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_indonesiana_big.png" group-title="Local Channel",916 Indonesiana TV HD
rtp://@239.1.1.176:9197
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_Jowo_channel.png" group-title="Local Channel", 917 Jowo HD
rtp://@239.1.2.212:9208


==

#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_useesport_newlogo.png" group-title="HD Channel",85 Usee Sports HD
rtp://@239.1.2.203:9180
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_useesports2_newlogo.png" group-title="HD Channel",86 Usee Sports 2 HD
rtp://@239.1.2.205:9186
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_seatoday_big.png" group-title="HD Channel",87 SEA Today HD
rtp://@239.1.2.70:8396
##broklin
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_useeprime_big1.png" group-title="HD Channel",88 Usee Prime HD
rtp://@239.1.1.252:9486
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_useephoto_big1.png" group-title="HD Channel",89 Usee Photo HD
rtp://@239.1.2.24:8118
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_tvri_big_hd.png" group-title="HD Channel",100 TVRI HD
rtp://@239.1.1.238:8016
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_metrotv_big1.png" group-title="HD Channel",101 METRO TV HD
rtp://@239.1.2.2:7986
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_cnnindonesia_big1.png" group-title="HD Channel",102 CNN Indonesia HD
rtp://@239.1.1.180:9054
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_transtv_big1.png" group-title="HD Channel",104 TransTV HD
rtp://@239.1.1.194:9138
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_trans7_big1.png" group-title="HD Channel",105 Trans7 HD
rtp://@239.1.1.222:9306
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_sctv_big1.png" group-title="HD Channel",107 SCTV HD
rtp://@239.1.2.58:8324
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_indosiar_big1.png" group-title="HD Channel",109 Indosiar HD
rtp://@239.1.1.214:8010
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-net-big1.png" group-title="HD Channel",112 Net TV HD
rtp://@239.1.1.158:8922
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_kompastv_big2.png" group-title="HD Channel",114 Kompas HD
rtp://@239.1.1.240:8017
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_beritasatu_big1.png" group-title="HD Channel",115 BTV HD
rtp://@239.1.1.114:9512
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_rtv_big2.png" group-title="HD Channel",118 RTV HD
rtp://@239.1.1.253:8018
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_antara_big1.png" group-title="HD Channel",124 Antara HD
rtp://@239.1.1.104:9511
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_ochannel_big.png" group-title="HD Channel",125 Moji HD
rtp://@239.1.1.10:9513
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_natgeo_big.png" group-title="HD Channel",201 National Geographic HD
rtp://239.1.1.243:9432
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_natgeowild_big.png" group-title="HD Channel",202 Natgeo Wild HD
rtp://@239.1.1.207:9216
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/crimeinvestigation.png" group-title="HD Channel",203 Crime & Investigation HD
rtp://@239.1.1.223:8012
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_cgtndocumentary_big1.png" group-title="HD Channel",204 CGTN Documentary HD
rtp://@239.1.2.4:7998
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_history_big.png" group-title="HD Channel",205 History Channel HD
rtp://@239.1.1.23:8112
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_discovery_big.png" group-title="HD Channel",207 Discovery HD
rtp://@239.1.1.247:9440
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-techstorm_big.png" group-title="HD Channel",209 TechStorm HD
rtp://@239.1.2.229:9330
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_davinci_big1.png" group-title="HD Channel",303 Da Vinci HD
rtp://@239.1.1.218:8011
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_nickelodeon_big.png" group-title="HD Channel",304 Nickelodeon HD
rtp://@239.1.1.14:7982
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_nickjr_big.png" group-title="HD Channel",305 Nick Junior HD
rtp://@239.1.1.162:7983
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_cartoonnetwork_big.png" group-title="HD Channel",306 Cartoon Network HD
rtp://@239.1.2.81:8083
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_boomerang_big.png" group-title="HD Channel",308 BOOMERANG HD
rtp://@239.1.1.163:8084
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_dreamworks_big1.png" group-title="HD Channel",310 DreamWork HD
rtp://@239.1.1.234:9222
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_moonbug_big.png" group-title="HD Channel",311 Moonbug Kids HD
rtp://@239.1.1.235:8593
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_mykids_big.png" group-title="HD Channel",313 MY KIDZ HD
rtp://@239.1.1.52:8416
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_indikids_big.png" group-title="HD Channel",314 indi kids HD
rtp://@239.1.1.201:9180
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_horee_big.png" group-title="HD Channel",315 Horee! HD
rtp://@239.1.1.225:8013
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_mentaritv_big.png" group-title="HD Channel",316 Mentari TV HD
rtp://@239.1.1.140:9515
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_afc_big.png" group-title="HD Channel",402 AFN HD
rtp://@239.1.2.13:8052
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_fashiontv_big1.png" group-title="HD Channel",404 Fashion TV HD
rtp://@239.1.2.237:9348
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-tlc_big.png" group-title="HD Channel",406 TLC HD
rtp://@239.1.2.235:9342
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/mtvlive.png" group-title="HD Channel",450 MTV Live HD
rtp://@239.1.2.16:8070
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_prambors_big1.png" group-title="HD Channel",453 Prambors HD
rtp://@239.1.1.254:8019
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_ikonser_big.png" group-title="HD Channel",459 i Konser HD
rtp://@239.1.2.221:9250
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_hgtv_big.png" group-title="HD Channel",500 HGTV HD
rtp://@239.1.2.34:8178
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_blueantext_big.png" group-title="HD Channel",501 Rock Action HD
rtp://@239.1.1.112:8646
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_animax_big.png" group-title="HD Channel",502 Animax HD
rtp://@239.1.1.142:8967
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_lifetime_big.png" group-title="HD Channel",505 Lifetime HD
rtp://@239.1.1.25:8124
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_kix_big.png" group-title="HD Channel",506 KIX HD
rtp://@239.1.2.207:9190
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-hits_big.png" group-title="HD Channel",507 Hits HD
rtp://@239.1.1.209:9228
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_warner_big.png" group-title="HD Channel",508 Warner HD
rtp://@239.1.2.244:9078
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_axn_big.png" group-title="HD Channel",509 AXN HD
rtp://@239.1.1.245:9436
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_blueant_big.png" group-title="HD Channel",511 Rock Entertainment HD
rtp://@239.1.2.76:9310
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_tvn_big.png" group-title="HD Channel",516 TVN HD
rtp://@239.1.2.211:9202
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/kbsworld.png" group-title="HD Channel",517 KBS World HD
rtp://@239.1.1.13:8052
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_aniplus_big1.png" group-title="HD Channel",518 Aniplus HD
rtp://@239.1.2.104:9526
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_nhkworld_big.png" group-title="HD Channel",519 NHK World Premium HD
rtp://@239.1.1.174:9018
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_kplus_big1.png" group-title="HD Channel",523 K+ HD
rtp://@239.1.1.202:9186
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_abcaustralia_big.png" group-title="HD Channel",531 ABC Autralia HD
rtp://@239.1.1.26:9519
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_arirang_big.png" group-title="HD Channel",532 Arirang HD
rtp://@239.1.2.107:9522
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_citradrama_big.png" group-title="HD Channel",534 Citra Drama HD
rtp://@239.1.1.230:9516
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_citradangdut_big.png" group-title="HD Channel",535 Citra Dangdut HD
rtp://@239.1.1.24:9517
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_sgem_big.png" group-title="HD Channel",536 GEM HD
rtp://@239.1.2.18:8082
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_sone_big.png" group-title="HD Channel",537 ONE HD
rtp://@239.1.2.21:8100
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-paramount_big.png" group-title="HD Channel",600 Paramount HD
rtp://@239.1.1.211:9240
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hbo.png" group-title="HD Channel",601 HBO HD
rtp://@239.1.1.203:9192
##################INDONESIA######################
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hbosignature.png" group-title="HD Channel",602 HBO Signature HD
rtp://@239.1.2.249:9378
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/cinemax.png" group-title="HD Channel",603 Cinemax HD
rtp://@239.1.2.247:9372
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hbohits.png" group-title="HD Channel",604 HBO Hits HD
rtp://@239.1.1.215:9264
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hbofamily.png" group-title="HD Channel",605 HBO Family HD
rtp://@239.1.2.245:9366
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-hitsmovie_big.png" group-title="HD Channel",606 Hits Movies HD
rtp://@239.1.1.190:9116
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/celectial.png" group-title="HD Channel",611 Celestial Movie HD
rtp://@239.1.1.232:8014
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-mycinema_big.png" group-title="HD Channel",612 My Cinema HD
rtp://@239.1.2.225:9318
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/tvnmovie.png" group-title="HD Channel",613 TVN Movies HD
rtp://@239.1.2.72:8408
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/cinemaworld.png" group-title="HD Channel",615 Cinema World HD
rtp://@239.1.2.80:8578
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-myfamily_big.png" group-title="HD Channel",616 My Family Channel HD
rtp://@239.1.1.237:9396
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_galaxy_big1.png" group-title="HD Channel",617 Galaxy HD
rtp://@239.1.1.136:8790
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_flik_big1.png" group-title="HD Channel",619 Flik HD
rtp://@239.1.1.239:9276
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_imc_big.png" group-title="HD Channel",620 IMC HD
rtp://@239.1.1.145:8844
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_galaxypremium_big.png" group-title="HD Channel",621 Galaxy Premium HD
rtp://@239.1.2.100:9518
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-mycinemaasia_big.png" group-title="HD Channel",624 My Cinema Asia HD
rtp://@239.1.1.231:8062
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_bein1_big1.png" group-title="HD Channel",701 Bein 1 HD
rtp://@239.1.1.248:9494
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_bein3_big1.png" group-title="HD Channel",702 Bein 3 HD
rtp://@239.1.1.249:9496
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_fight_big1.png" group-title="HD Channel",704 Fight Sport HD
rtp://@239.1.2.209:9196
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_spotv_hd_big.png" group-title="HD Channel",705 SPOTV HD
rtp://@239.1.1.109:8623
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_spotv2_hd_big.png" group-title="HD Channel",706 SPOTV 2 HD
rtp://@239.1.1.196:9145
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_nba_big1.png" group-title="HD Channel",708 NBA TV HD
rtp://@239.1.2.210:9444
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_egg_big1.png" group-title="HD Channel",709 Egg HD
rtp://@239.1.1.235:8015
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_new-horizonsport_big.png" group-title="HD Channel",714 Horizon Sports HD
rtp://@239.1.2.201:9174
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/cnn.png" group-title="HD Channel",801 CNN HD
rtp://@239.1.1.246:9438
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_bloomberg_big1.png" group-title="HD Channel",802 Bloomberg HD
rtp://@239.1.2.105:9520
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_cnbcasias_big.png" group-title="HD Channel",803 CNBC Asia HD
rtp://@239.1.1.46:8413
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_newsasia_big1.png" group-title="HD Channel",804 Channel News Asia HD
rtp://@239.1.2.23:8112
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_aljazeera_big1.png" group-title="HD Channel",805 Al Jazeera HD
rtp://@239.1.2.8:8022
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_france24_big.png" group-title="HD Channel",806 France 24 HD
rtp://@239.1.2.22:8106
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_nhkworld_big.png" group-title="HD Channel",807 NHK World Japan HD
rtp://@239.1.2.239:9354
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_dwtv_big.png" group-title="HD Channel",808 DW HD
rtp://@239.1.2.243:9360
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_tvbsnews_big.png" group-title="HD Channel",809 TVBS News HD
rtp://@239.1.1.48:8414
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_trtworld_small.png" group-title="HD Channel",810 TRT World HD
rtp://@239.1.1.250:9518
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_cnbcid_big.png" group-title="HD Channel",811 CNBC Indonesia HD
rtp://@239.1.2.94:9448
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_rri_big1.png" group-title="HD Channel",887 RRI Net HD
rtp://@239.1.1.130:9514
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_indonesiana_big.png" group-title="HD Channel",916 Indonesiana TV HD
rtp://@239.1.1.176:9197
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_Jowo_channel.png" group-title="HD Channel", 917 Jowo HD
rtp://@239.1.2.212:9208


===

#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hbo.png" group-title="Dolby",891 HBO Dolby HD
rtp://@239.1.2.114:9428
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hbosignature.png" group-title="Dolby",892 HBO Signature Dolby HD
rtp://@239.1.2.116:9404
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hbohits.png" group-title="Dolby",893 HBO Hits Dolby HD
rtp://@239.1.2.204:9182
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/hbofamily.png" group-title="Dolby",894 HBO Family Dolby HD
rtp://@239.1.2.202:9176
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/cinemax.png" group-title="Dolby",895 Cinemax Dolby HD
rtp://@239.1.2.206:9186


===
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_useeprime_big1.png" group-title="Gen Entertainment",88 USee Prime HD
rtp://@239.1.1.252:9486
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_blueantext_big.png" group-title="Gen Entertainment",501 Rock Action HD
rtp://@239.1.1.112:8646


===

#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_dramakorealbs_big.png" group-title="Lifestyle",113 Drama Korea LBS
rtp://@239.1.2.101:9521
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_iberkah.png" group-title="Lifestyle",117 iBerkah
rtp://@239.1.1.12:7984
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-atv-big1.png" group-title="Lifestyle",121 ATV
rtp://@239.1.2.88:8308


===

#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_indonesiana_big.png" group-title="Knowledge",200 Indonesiana TV
rtp://@239.1.1.206:9199
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_indonesiana_big.png" group-title="Knowledge",916 Indonesiana TV HD
rtp://@239.1.1.176:9197


===

#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_seatoday_big.png" group-title="News",87 SEA Today HD
rtp://@239.1.2.70:8396
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-metrotv.png" group-title="News",101 Metro TV HD
rtp://@239.1.2.2:7986
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_cnnindonesia_big1.png" group-title="News",102 CNN Indonesia HD
rtp://@239.1.1.180:9054
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-tvone-big1.png" group-title="News",103 TV One
rtp://@239.1.1.31:8160
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo-kompastv-big1.png" group-title="News",114 Kompas TV HD
rtp://@239.1.1.240:8017
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_beritasatu_big1.png" group-title="News",115 BTV HD
rtp://@239.1.1.114:9512
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_idx_big.png" group-title="News",119 IDX Channel
rtp://@239.1.2.248:9398
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_antara_big1.png" group-title="News",124 Antara HD
rtp://@239.1.1.104:9511
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_inews_big.png" group-title="News",129 iNews
rtp://@239.1.1.212:8967
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_mncnews2_big.png" group-title="News",134 MNC News
rtp://@239.1.1.146:7985
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_cnbcid_big.png" group-title="News",135 CNBC Indonesia HD
rtp://@239.1.2.94:9448
#EXTINF:-1 tvg-logo="https://raw.githubusercontent.com/chae48/woyeoye/main/logo/logo_abcaustralia_big.png" group-title="News",531 ABC Australia HD
rtp://@239.1.1.26:9519

